name: Language Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.md'
      - '**.mdx'
      - '.github/workflows/lang-check.yml'
      - 'lang-check/**'

  workflow_dispatch:

jobs:
  lang-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Run language check script
        id: lang-check
        env:
          DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
        run: |
          chmod +x ./lang-check/git-diff.sh
          output=$(./lang-check/git-diff.sh)
          echo "$output"
          
          if echo "$output" | grep -q "❌"; then
            echo "检查发现问题，PR 不予通过"
            echo "::set-output name=result::检查发现问题，PR 不予通过"
            exit 1
          else
            echo "检查通过"
            echo "::set-output name=result::检查通过"
            exit 0
          fi

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = core.getInput('result');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Language Check Result:\n\n${output}`
            })